# This is the configure file for pnohs ---- a framewor for hydrology simulation.
#
# visite https://github.com/toml-lang/toml
# and https://github.com/toml-lang/toml/blob/master/versions/cn/toml-v0.4.0.md
# to see more information about toml standard.
#

title = "Configure file for pnohs"
version = "0.1.0"

[dispatch]
dispatch_file = "pnohs.dis"
dob = 1979-05-27T07:32:00-08:00 # 日期是一等公民

[simulation]
time_steps = 100

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]
  #你可以使用空格、制表符进行缩进，或者根本不缩进。TOML不关心缩进。
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# 数组内可以混入换行符
hosts = [
  "alpha",
  "omega"
]
