image: genshen/mpich-pkg:0.2.0-beta
#services:
#  - postgres

before_script:
  - pkg fetch
  - pkg install

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - vendor/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake ../
  - make
