image: hpcer/hpcdev:pkg-0.3.0
#services:
#  - postgres

cache:
  key: vendor_version_gtest_1.10.0
  paths:
  - vendor/

stages:
  - fetch
  - build
#  - test
#  - deploy

fetch:
  stage: fetch
  tags:
    - cpp
    - pkg
  script:
    - pkg fetch
    - pkg install
  artifacts:
    untracked: true

build:
  stage: build
  tags:
    - cpp
    - pkg
  script:
    - cmake -Bcmake-build -DCMAKE_BUILD_TYPE=Debug -H.
    - make -Ccmake-build
#  artifacts:
#    untracked: true
  dependencies:
    - fetch
