cache:
  key: pkg_cache_v1
  paths:
  - pkg_cache

stages:
  - fetch
  - build
  - test
  - deploy

fetch:
  stage: fetch
  image:
    name: genshen/pkg:0.4.1-clang10-mpi
    entrypoint: [""]
  tags:
    - cpp
    - pkg
  before_script:
    - mkdir -p pkg_cache
    - ln -s $(pwd)/pkg_cache ~/.pkg
  script:
    - pkg fetch
    - pkg install
    - rm -rf vendor/cache
  artifacts:
    untracked: true

build:
  stage: build
  image:
    name: genshen/pkg:0.4.1-clang10-mpi
    entrypoint: [""]
  tags:
    - cpp
    - pkg
  script:
    - cmake -B./cmake-build-debug -S./ -DCMAKE_CXX_FLAGS_DEBUG="-fprofile-instr-generate -fcoverage-mapping" -DCMAKE_C_FLAGS_DEBUG="-fprofile-instr-generate -fcoverage-mapping" -DCMAKE_BUILD_TYPE=Debug
    - cmake --build ./cmake-build-debug
  artifacts:
    paths:
      - cmake-build-debug/bin
  dependencies:
    - fetch

test:
  stage: test
  image:
    name: genshen/pkg:0.4.1-clang10-mpi
    entrypoint: [""]
  tags:
    - cpp
    - pkg
  variables:
    COV_IGNORE_FILES: >
      --ignore-filename-regex=/usr/local/*
      --ignore-filename-regex=".*test/unit/*."
      --ignore-filename-regex=".*vendor/*."
  script:
    - mkdir -p coverage
    - LLVM_PROFILE_FILE="pnohs-test.profraw" ./cmake-build-debug/bin/pnohs-unit-tests
    - llvm-profdata merge -sparse pnohs-test.profraw -o pnohs-test.profdata
    - llvm-cov report ./cmake-build-debug/bin/pnohs-unit-tests  -instr-profile=pnohs-test.profdata ${COV_IGNORE_FILES}
    - llvm-cov show ./cmake-build-debug/bin/pnohs-unit-tests -instr-profile=pnohs-test.profdata --format=html --summary-only --output-dir=./coverage ${COV_IGNORE_FILES}
  artifacts:
    paths:
      - coverage
  dependencies:
    - build

pages:
  tags: [pages]
  stage: deploy
  image:
    name: alpine:3.12
  script:
    - mv coverage public
  artifacts:
    paths:
      - public
  dependencies:
    - test
  only:
    - master
