image: genshen/mpich-with-netlogin-pkg:3.2.1
#services:
#  - postgres

before_script:
  - curl_netlogin # login network first if necessary.
  - pkg install

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - vendor/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake ../
  - make
