title = "Config file for pnohs."

[application]
app_name = "pnohs"
app_name_capital = "PNOHS"
describe = "pnohs is Not Only Hydrological Simulation."
author = "genshen"

[code]
head_define_prefix = "PNOHS" # show in .h file for file define,usually its equal to value application.app_name_capital.

[git]
template_url = "http://genshen:genshen1234@git.gensh.me/genshen/pencil-template.git"  # for basic auth: https://user:pass@git.example.com/project.git
init_git_repository = true  # initial a git repository after created this project.
repository_url = "http://git.gensh.me/HPCer/hydrology/pnohs.git"

[dependency]
mpi_enable = true
openmp_enable = true

    [dependency.test]
    enable = true
    mpi_enable = true
    test_library = "catch2"   # googletest or catch2

    [dependency.test.config]
        [dependency.test.config.googletest]
        url = "https://github.com/google/googletest.git"
        version = "release-1.8.0"
        path = "test/external/googletest"

        [dependency.test.config.catch2]
        url = "https://raw.githubusercontent.com/CatchOrg/Catch2/master/single_include/catch.hpp"
        version = "v2.0.1"
        path = "test/external/catch2/catch.hpp"

[template]
included_files = ["*.cpp", "*.h","*CMakeLists.txt","README.md"]
excluded_files = ["*.o", "test/external/*"]  # use unix style
