// The file test_config.h is generated by CMake, DO NOT modify it.
#ifndef _TEST_CONFIG_H
#define _TEST_CONFIG_H

/* #undef CATCH2_TEST_ENABLE_FLAG */
/* #undef GOOGLE_TEST_ENABLE_FLAG */
#define TEST_MPI_ENABLE_FLAG

#endif // _TEST_CONFIG_H
